language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

before_script:
  - go vet -x ./...

script:
  - GORACE="halt_on_error=1" go test -v -race -cover -covermode atomic ./...
  - GORACE="halt_on_error=1" go test -v -race -bench . -benchmem
  - GORACE="halt_on_error=1" go test -v -bench . -benchmem
